

quarkus.rest-client.frankfurter-api.url=https://api.frankfurter.app
quarkus.rest-client.follow-redirects=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=*